dist: xenial
group: stable

language: scala
jdk: openjdk8

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

matrix:
  include:
    - scala: 2.12.10
      jdk: openjdk11
    - scala: 0.17.0-RC1
      jdk: openjdk8
      script: sbt ++${TRAVIS_SCALA_VERSION}! expectyJVM/test
    - scala: 2.11.12
      sudo: required
      before_script:
        - sudo chmod +x /usr/local/bin/sbt
      before_install:
        - sudo apt-get update
        - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      script:
        - sbt ++${TRAVIS_SCALA_VERSION}! expectyNative/test

script: sbt ++${TRAVIS_SCALA_VERSION}! expectyJVM/test expectyJS/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
